#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "FreeRTOS.h"
#include "task.h"
#include "sys_init.h"
#include "lwip_network.h"
#include "wifi_api.h"
#if defined(MTK_MINICLI_ENABLE)
#include "cli_def.h"
#endif
#ifdef MTK_JR_ENABLE
#include "jerry.h"
#endif

#include "bsp_gpio_ept_config.h"
#include "app_common.h"

void js_lib_init() {
  /* <%= ML_INIT %> */
}

/**
  * @brief  Main program
  * @param  None
  * @retval None
  */
int fota_mode = 0;

void js_init() {
  // remember to add `var global={};`
  char script [] = <%- JS_CODE %>;

  jerry_init (JERRY_FLAG_EMPTY);
  jerry_api_value_t eval_ret;

  js_lib_init();

  jerry_api_eval (script, strlen (script), false, false, &eval_ret);
  jerry_api_release_value (&eval_ret);
  // jerry_cleanup ();
  vTaskDelete(NULL);
}

int main(void)
{
    /* Do system initialization, eg: hardware, nvdm, logging and random seed. */
    system_init();


    /* bsp_ept_gpio_setting_init() under driver/board/mt76x7_hdk/ept will initialize the GPIO settings
     * generated by easy pinmux tool (ept). ept_*.c and ept*.h are the ept files and will be used by
     * bsp_ept_gpio_setting_init() for GPIO pinumux setup.
     */
    bsp_ept_gpio_setting_init();


    /* User initial the parameters for wifi initial process,  system will determin which wifi operation mode
     * will be started , and adopt which settings for the specific mode while wifi initial process is running*/
    // wifi_config_t config = {0};
    // config.opmode = WIFI_MODE_STA_ONLY;
    // strcpy((char *)config.sta_config.ssid, (const char *)"mcs");
    // strcpy((char *)config.sta_config.password, (const char *)"mcs12345678");
    // config.sta_config.ssid_length = strlen((const char *)config.sta_config.ssid);
    // config.sta_config.password_length = strlen((const char *)config.sta_config.password);


    //  Initialize wifi stack and register wifi init complete event handler,
    //  * notes:  the wifi initial process will be implemented and finished while system task scheduler is running,
    //  *            when it is done , the WIFI_EVENT_IOT_INIT_COMPLETE event will be triggered
    // wifi_init(&config, NULL);
    // wifi_connection_register_event_handler(WIFI_EVENT_IOT_INIT_COMPLETE, wifi_mode_connected);


    // /* Tcpip stack and net interface initialization,  dhcp client, dhcp server process initialization*/
    // lwip_network_init(config.opmode);
    // lwip_net_start(config.opmode);


    // /* Create a user task for demo when and how to use wifi config API  to change WiFI settings*/
    // xTaskCreate(user_wifi_app_entry, "User app", 1024, NULL, 1, NULL);


    /* Initialize cli task to enable user input cli command from uart port.*/
#if defined(MTK_MINICLI_ENABLE)
    cli_def_create();
    cli_task_create();
#endif
    xTaskCreate(js_init,"js_init", 15096, NULL, 2, NULL);

    vTaskStartScheduler();

    /* If all is well, the scheduler will now be running, and the following line
    will never be reached.  If the following line does execute, then there was
    insufficient FreeRTOS heap memory available for the idle and/or timer tasks
    to be created.  See the memory management section on the FreeRTOS web site
    for more details. */
    for ( ;; );
}

